# .github/workflows/infra-ci.yaml
name: Infrastructure CI

on:
  push:
    branches:
      - 'develop'
      - 'main'
    paths:
      - 'infra/**'

jobs:
  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: infra
          format: sarif
          out: tfsec.sarif

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infra
          framework: terraform
          output_format: sarif
          output_file: checkov.sarif
          
      - name: Upload SARIF files
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: infra

  cost-estimation:
    name: Cost Estimation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost cost estimate
        working-directory: ./infra
        run: |
          infracost breakdown --path . \
            --format html \
            --out-file infracost-report.html \
            --show-skipped

      - name: Post Infracost comment
        if: github.event_name == 'pull_request'
        uses: infracost/actions/comment@v2
        with:
          path: ./infra/infracost-report.html
          sync-behavior: update

      - name: Archive cost report
        uses: actions/upload-artifact@v3
        with:
          name: infracost-report
          path: ./infra/infracost-report.html

  terraform-plan:
    name: Terraform Plan
    needs: [security-scan, cost-estimation]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Terraform Format Check
        working-directory: ./infra
        run: terraform fmt -check

      - name: Terraform Plan
        working-directory: ./infra
        run: terraform plan -out=tfplan